<html>
<div id="tos_id">
        <h2>Terms of Service:</h2><br />
        <p>This Terms of Service is created under the Creative Commons Sharealike license.</p>
        <p>The following terms and conditions govern all use of the FicForest__.com website and all content, services and products available at or through the website. The Website is owned and operated by FicForest__. The Website is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies and procedures that may be published from time to time on this Site.</p>
        <p>Please read this Agreement carefully before accessing or using the Website. By accessing or using any part of the web site, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access the Website or use any services. If these terms and conditions are considered an offer, acceptance is expressly limited to these terms.</p>
        <ol>
        <li><strong>Your Account and Site.</strong> If you create a entry on the Website, you are responsible for maintaining the security of your account and story, and you are fully responsible for all activities that occur under the account and any other actions taken in connection with the account. You must not construct story in a misleading or unlawful manner, including in a manner intended to trade on the name or reputation of others, and FicForest__ may change or remove any description it considers inappropriate or unlawful, or otherwise likely to cause FicForest liability. You must immediately notify FicForest of any unauthorized uses of your story, your account or any other breaches of security. FicForest will not be liable for any acts or omissions by You, including any damages of any kind incurred as a result of such acts or omissions.</li>
        <li><strong>Responsibility of Contributors.</strong> If you operate a story, comment on a story, post material to the Website, post links on the Website, or otherwise make (or allow any third party to make) material available by means of the Website (any such material, “Content”), You are entirely responsible for the content of, and any harm resulting from, that Content. By making Content available, you represent and warrant that:
        <ul>
        <li>the downloading, copying and use of the Content will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark or trade secret rights, of any third party;</li>
        <li>if your employer has rights to intellectual property you create, you have either (i) received permission from your employer to post or make available the Content, including but not limited to any software, or (ii) secured from your employer a waiver as to all rights in or to the Content;</li>
        <li>you have fully complied with any third-party licenses relating to the Content, and have done all things necessary to successfully pass through to end users any required terms;</li>
        <li class="important">the Content is not spam, is not machine- or randomly-generated, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or boost the search engine rankings of third party sites, or to further unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing);</li>
        <li>the Content does not contain threats or incite violence towards individuals or entities, and does not violate the privacy or publicity rights of any third party;</li>
        <li>your story is not getting advertised via unwanted electronic messages such as spam links on newsgroups, email lists, other storys and web sites, and similar unsolicited promotional methods;</li>
        <li>your story is not named in a manner that misleads your readers into thinking that you are another person or company. </li>
        <li>you have, in the case of Content that includes computer code, accurately categorized and/or described the type, nature, uses and effects of the materials, whether requested to do so by FicForest or otherwise.</li>
        </ul>
        <p>By submitting Content to FicForest, you grant FicForest a world-wide, royalty-free, and non-exclusive license to reproduce, modify, adapt and publish the Content solely for the purpose of displaying, distributing and promoting your story. If you delete Content, FicForest will use reasonable efforts to remove it from the Website, but you acknowledge that caching or references to the Content may not be made immediately unavailable.</p>
        <p>Without limiting any of those representations or warranties, FicForest has the right (though not the obligation) to, in FicForest’s sole discretion (i) refuse or remove any content that, in FicForest’s reasonable opinion, violates any FicForest policy or is in any way harmful or objectionable, or (ii) terminate or deny access to and use of the Website to any individual or entity for any reason, in FicForest’s sole discretion. FicForest will have no obligation to provide a refund of any amounts previously paid.</li>
        <li><strong>Responsibility of Website Visitors.</strong> FicForest has not reviewed, and cannot review, all of the material, posted to the Website, and cannot therefore be responsible for that material’s content, use or effects. By operating the Website, FicForest does not represent or imply that it endorses the material there posted, or that it believes such material to be accurate, useful or non-harmful. You are responsible for taking precautions as necessary to protect yourself from harmful or destructive content. The Website may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. The Website may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstated. FicForest disclaims any responsibility for any harm resulting from the use by visitors of the Website, or from any downloading by those visitors of content there posted.</li>
        <li><strong>Content Posted on Other Websites.</strong> We have not reviewed, and cannot review, all of the material made available through the websites and webpages to which ec2-50-19-29-217.compute-1.amazonaws.com.com links, and that link to ec2-50-19-29-217.compute-1.amazonaws.com.com. FicForest does not have any control over those non-ec2-50-19-29-217.compute-1.amazonaws.com websites and webpages, and is not responsible for their contents or their use. By linking to a non-ec2-50-19-29-217.compute-1.amazonaws.com website or webpage, FicForest does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself from harmful or destructive content. FicForest disclaims any responsibility for any harm resulting from your use of non-ec2-50-19-29-217.compute-1.amazonaws.com websites and webpages.</li>
        <li><strong>Copyright Infringement and DMCA Policy.</strong> As FicForest asks others to respect its intellectual property rights, it respects the intellectual property rights of others. If you believe that material located on or linked to by ec2-50-19-29-217.compute-1.amazonaws.com.com violates your copyright, you are encouraged to notify FicForest (see our "Contact Us" page). FicForest will respond to all such notices, including as required or appropriate by removing the infringing material or disabling all links to the infringing material. FicForest will terminate a visitor&#8217;s access to and use of the Website if, under appropriate circumstances, the visitor is determined to be a repeat infringer of the copyrights or other intellectual property rights of FicForest or others.</li>
        <li><strong>Intellectual Property.</strong> This Agreement does not transfer from FicForest to you any FicForest or third party intellectual property, and all right, title and interest in and to such property will remain (as between the parties) solely with FicForest. FicForest, ec2-50-19-29-217.compute-1.amazonaws.com, ec2-50-19-29-217.compute-1.amazonaws.com.com, the ec2-50-19-29-217.compute-1.amazonaws.com.com logo, and all other trademarks, service marks, graphics and logos used in connection with ec2-50-19-29-217.compute-1.amazonaws.com.com, or the Website are trademarks or registered trademarks of FicForest or FicForest’s licensors. Other trademarks, service marks, graphics and logos used in connection with the Website may be the trademarks of other third parties. Your use of the Website grants you no right or license to reproduce or otherwise use any FicForest or third-party trademarks.</li>
        <li><strong>Changes. </strong>FicForest reserves the right, at its sole discretion, to modify or replace any part of this Agreement. It is your responsibility to check this Agreement periodically for changes. Your continued use of or access to the Website following the posting of any changes to this Agreement constitutes acceptance of those changes. FicForest may also, in the future, offer new services and/or features through the Website (including, the release of new tools and resources). Such new features and/or services shall be subject to the terms and conditions of this Agreement. <strong><br />
        </strong></li>
        <li><strong>Termination. </strong>FicForest may terminate your account access to all or any part of the Website at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement or your ec2-50-19-29-217.compute-1.amazonaws.com.com account (if you have one), you may simply discontinue using the Website. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability. <strong><br />
        </strong></li>
        <li class="important"><strong>Disclaimer of Warranties.</strong> The Website is provided &#8220;as is&#8221;. FicForest and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither FicForest nor its suppliers and licensors, makes any warranty that the Website will be error free or that access thereto will be continuous or uninterrupted. If you&#8217;re actually reading this, <a href="http://wordpress.com/tos/treat/">here&#8217;s a treat</a>. You understand that you download from, or otherwise obtain content or services through, the Website at your own discretion and risk.</li>
        <li class="important"><strong>Limitation of Liability.</strong> In no event will FicForest, or its suppliers or licensors, be liable with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement for substitute products or services; (iii) for interruption of use or loss or corruption of data; or (iv) for any amounts that exceed the fees paid by you to FicForest under this agreement during the twelve (12) month period prior to the cause of action. FicForest shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law.</li>
</div>
</html>

